"""initial schema

Revision ID: 443727b49ab2
Revises: 
Create Date: 2026-08-15 22:03:28.149783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443727b49ab2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    # Check if tables exist to make the migration idempotent.
    existing = {row[0] for row in conn.exec_driver_sql(
        "SELECT tablename FROM pg_tables WHERE schemaname='public'"
    ).fetchall()}

    # ### commands auto generated by Alembic - please adjust! ###
    if 'api_keys' not in existing:
        op.create_table('api_keys',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('key_hash', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key_hash')
        )
        op.create_index('idx_apikeys_status', 'api_keys', ['status'], unique=False)
        op.create_index('idx_apikeys_tenant', 'api_keys', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    if 'tasks' not in existing:
        op.create_table('tasks',
        sa.Column('task_id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('task_type', sa.String(length=64), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.Column('error', sa.String(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('timeout_seconds', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('lease_owner', sa.String(length=64), nullable=True),
        sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('task_id')
        )
        op.create_index('idx_tasks_agent_status', 'tasks', ['agent_id', 'status'], unique=False)
        op.create_index('idx_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
        op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
        op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
        op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    else:
        # Add columns that might be missing (e.g., from ensure_schema create_all)
        columns = {row[0] for row in conn.exec_driver_sql(
            "SELECT column_name FROM information_schema.columns WHERE table_name='tasks'"
        ).fetchall()}
        if 'lease_owner' not in columns:
            op.add_column('tasks', sa.Column('lease_owner', sa.String(length=64), nullable=True))
        if 'lease_expires_at' not in columns:
            op.add_column('tasks', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    if 'tenants' not in existing:
        op.create_table('tenants',
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('quota', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('extra_metadata', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('tenant_id')
        )
        op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_index('idx_tasks_status_created', table_name='tasks')
    op.drop_index('idx_tasks_agent_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index('idx_apikeys_tenant', table_name='api_keys')
    op.drop_index('idx_apikeys_status', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
